language: java

jdk:
  - oraclejdk8	
  - openjdk8	
  - openjdk10
  - openjdk11

addons:
  hostname: dropwizard-jobs-ci

before_install:
  - ulimit -c unlimited -S

cache:
  directories:
    - "$HOME/.m2"

env:
  global:
    - JAVA_OPTS: "'-Xms512m -Xmx2g'"
    - secure: LGD9kWPTbRthg72NCCf8e8ztAugu4AFvivb7wBUYbRpFV8wwu3okLpWw3kCIuIsBnFA89nwoqPXqOr1EjOXMVj3CFbi1vlB49MF22vmfjMgpDXmaxeqO2FSclN+r8gvLJ4v7yPocTnwOGVTMQsnb5IhPLf4UZsY2mfwEnllsdO0=
    - secure: NK5FIaI/LKb34WhkHUdj91HAj++BRKMe4iPA8BTOmWm6q8auL/Tw5tpEU6uwbNNINDRqEg3qv8Oy+Vccv+AJLiNqKvIdCwFTpTNXPdqa5Vj4x5PtIOIxjtiVgK9PZJvr+cCsYX5/5pFdFcg3BE24ETTF2meXmzsEjoDELvrT0Tc=

before_install:
  - ulimit -c unlimited -S
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central if tests are successful & tag is set
after_success:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    - echo ${TRAVIS_TAG+x}
    - echo $project_version
    - echo $jdk
    - test ${TRAVIS_TAG+x} != "x" && 
           $jdk = "openjdk11" &&
      mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
    
before_deploy:
  - git config --local user.name "hakandilek"
  - git config --local user.email "hakandilek@gmail.com"
  - git tag $project_version

deploy:
  provider: releases
  api_key:
    secure: fzMoX/r+9Kyaklq5fkZPtmfH3Gmjl1sfKOUWARnx+RiWHYK+L78MINi2kUuADSEHphKbHtzKum82byFlx6qc/xP+Mp38SVB6sRNBVab42vtKlZOZcwdUf1ZoQvoJ5lyArjJ3KjaZLb2/DAtKfjTF/5YEYuTchaUb9pPWTyeEP5Q=
  file: 
    - dropwizard-jobs-core/target/dropwizard-jobs-core-$project_version.jar
    - dropwizard-jobs-guice/target/dropwizard-jobs-guice-$project_version.jar
    - dropwizard-jobs-spring/target/dropwizard-jobs-spring-$project_version.jar
  skip_cleanup: true
  on:
    repo: dropwizard-jobs/dropwizard-jobs
    tags: true
  name: dropwizard-jobs-$project_version
